<a href="https://colab.research.google.com/github/Mhammad-riyaz/ML/blob/main/linear_algebra_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
x = np.array([1,2,4,5],dtype=np.float16)
x


array([1., 2., 4., 5.], dtype=float16)

In [6]:

len(x)


4

In [7]:
x.shape


(4,)

In [8]:
type(x)

numpy.ndarray

In [10]:
x_t = x.T
x_t

array([1., 2., 4., 5.], dtype=float16)

In [11]:
x_t.shape

(4,)

In [13]:
y = np.array([[1,2,3,4]])
y.shape

(1, 4)

In [15]:
y_t = y.T
y_t

array([[1],
       [2],
       [3],
       [4]])

In [16]:
y_t.shape

(4, 1)